### ISSUE TITLE
0.7.0: pytest test suite not ready for `pydantic` 2.x

### ISSUE THREAD

**Issue by kloczek** [samuelcolvin/dirty-equals#87] opened 2023-10-17 13:19 UTC
Looks like current test suite is not redy for latest `pydantic` 2.4.2.
<details>

```console
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-dirty-equals-0.7.0-2.fc35.x86_64/usr/lib64/python3.8/site-packages:/home/tkloczko/rpmbuild/BUILDROOT/python-dirty-equals-0.7.0-2.fc35.x86_64/usr/lib/python3.8/site-packages
+ /usr/bin/pytest -ra -m 'not network' --ignore tests/test_docs.py
============================= test session starts ==============================
platform linux -- Python 3.8.18, pytest-7.4.2, pluggy-1.3.0
rootdir: /home/tkloczko/rpmbuild/BUILD/dirty-equals-0.7.0
configfile: pyproject.toml
testpaths: tests
collected 547 items

tests/test_base.py .............................                         [  5%]
tests/test_boolean.py ............................................       [ 13%]
tests/test_datetime.py ................................................. [ 22%]
                                                                         [ 22%]
tests/test_dict.py ..................................................... [ 31%]
.....                                                                    [ 32%]
tests/test_inspection.py ............................                    [ 38%]
tests/test_list_tuple.py ............................................... [ 46%]
...............................                                          [ 52%]
tests/test_numeric.py .................................................. [ 61%]
.................................                                        [ 67%]
tests/test_other.py .................................................... [ 76%]
...........................FFFFFFFF................................      [ 89%]
tests/test_strings.py .................................................. [ 98%]
.........                                                                [100%]

=================================== FAILURES ===================================
_________________ test_is_url_true[https://example.com-IsUrl] __________________

other = 'https://example.com', dirty = IsUrl

    @pytest.mark.parametrize(
        'other,dirty',
        [
            ('https://example.com', IsUrl),
            ('https://example.com', IsUrl(scheme='https')),
            ('postgres://user:pass@localhost:5432/app', IsUrl(postgres_dsn=True)),
        ],
    )
    def test_is_url_true(other, dirty):
>       assert other == dirty

tests/test_other.py:283:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
dirty_equals/_base.py:26: in __eq__
    return self() == other
dirty_equals/_base.py:104: in __eq__
    self._was_equal = self.equals(other)
dirty_equals/_other.py:264: in equals
    parsed = self.parse_obj_as(self.url_type, other)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

args = (<class 'pydantic_core._pydantic_core.Url'>, 'https://example.com')
kwargs = {}

    @functools.wraps(arg)
    def wrapper(*args, **kwargs):
>       warnings.warn(msg, category=category, stacklevel=stacklevel + 1)
E       pydantic.warnings.PydanticDeprecatedSince20: parse_obj_as is deprecated. Use pydantic.TypeAdapter.validate_python instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.4/migration/

/usr/lib/python3.8/site-packages/typing_extensions.py:2359: PydanticDeprecatedSince20
_________________ test_is_url_true[https://example.com-dirty1] _________________

other = 'https://example.com'
dirty = IsUrl(<class 'pydantic_core._pydantic_core.Url'>)

    @pytest.mark.parametrize(
        'other,dirty',
        [
            ('https://example.com', IsUrl),
            ('https://example.com', IsUrl(scheme='https')),
            ('postgres://user:pass@localhost:5432/app', IsUrl(postgres_dsn=True)),
        ],
    )
    def test_is_url_true(other, dirty):
>       assert other == dirty

tests/test_other.py:283:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
dirty_equals/_base.py:104: in __eq__
    self._was_equal = self.equals(other)
dirty_equals/_other.py:264: in equals
    parsed = self.parse_obj_as(self.url_type, other)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

args = (<class 'pydantic_core._pydantic_core.Url'>, 'https://example.com')
kwargs = {}

    @functools.wraps(arg)
    def wrapper(*args, **kwargs):
>       warnings.warn(msg, category=category, stacklevel=stacklevel + 1)
E       pydantic.warnings.PydanticDeprecatedSince20: parse_obj_as is deprecated. Use pydantic.TypeAdapter.validate_python instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.4/migration/

/usr/lib/python3.8/site-packages/typing_extensions.py:2359: PydanticDeprecatedSince20
_______ test_is_url_true[postgres://user:pass@localhost:5432/app-dirty2] _______

other = 'postgres://user:pass@localhost:5432/app'
dirty = IsUrl(typing_extensions.Annotated[pydantic_core._pydantic_core.MultiHostUrl, UrlConstraints(max_length=None, allowed_s...+py-postgresql', 'postgresql+pygresql'], host_required=True, default_host=None, default_port=None, default_path=None)])

    @pytest.mark.parametrize(
        'other,dirty',
        [
            ('https://example.com', IsUrl),
            ('https://example.com', IsUrl(scheme='https')),
            ('postgres://user:pass@localhost:5432/app', IsUrl(postgres_dsn=True)),
        ],
    )
    def test_is_url_true(other, dirty):
>       assert other == dirty

tests/test_other.py:283:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
dirty_equals/_base.py:104: in __eq__
    self._was_equal = self.equals(other)
dirty_equals/_other.py:264: in equals
    parsed = self.parse_obj_as(self.url_type, other)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

args = (typing_extensions.Annotated[pydantic_core._pydantic_core.MultiHostUrl, UrlConstraints(max_length=None, allowed_scheme...st_required=True, default_host=None, default_port=None, default_path=None)], 'postgres://user:pass@localhost:5432/app')
kwargs = {}

    @functools.wraps(arg)
    def wrapper(*args, **kwargs):
>       warnings.warn(msg, category=category, stacklevel=stacklevel + 1)
E       pydantic.warnings.PydanticDeprecatedSince20: parse_obj_as is deprecated. Use pydantic.TypeAdapter.validate_python instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.4/migration/

/usr/lib/python3.8/site-packages/typing_extensions.py:2359: PydanticDeprecatedSince20
________________ test_is_url_false[https://example.com-dirty0] _________________

other = 'https://example.com'
dirty = IsUrl(typing_extensions.Annotated[pydantic_core._pydantic_core.MultiHostUrl, UrlConstraints(max_length=None, allowed_s...+py-postgresql', 'postgresql+pygresql'], host_required=True, default_host=None, default_port=None, default_path=None)])

    @pytest.mark.parametrize(
        'other,dirty',
        [
            ('https://example.com', IsUrl(postgres_dsn=True)),
            ('https://example.com', IsUrl(scheme='http')),
            ('definitely not a url', IsUrl),
            (42, IsUrl),
            ('https://anotherexample.com', IsUrl(postgres_dsn=True)),
        ],
    )
    def test_is_url_false(other, dirty):
>       assert other != dirty

tests/test_other.py:297:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
dirty_equals/_base.py:114: in __ne__
    return not self.equals(other)
dirty_equals/_other.py:264: in equals
    parsed = self.parse_obj_as(self.url_type, other)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

args = (typing_extensions.Annotated[pydantic_core._pydantic_core.MultiHostUrl, UrlConstraints(max_length=None, allowed_scheme...resql+pygresql'], host_required=True, default_host=None, default_port=None, default_path=None)], 'https://example.com')
kwargs = {}

    @functools.wraps(arg)
    def wrapper(*args, **kwargs):
>       warnings.warn(msg, category=category, stacklevel=stacklevel + 1)
E       pydantic.warnings.PydanticDeprecatedSince20: parse_obj_as is deprecated. Use pydantic.TypeAdapter.validate_python instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.4/migration/

/usr/lib/python3.8/site-packages/typing_extensions.py:2359: PydanticDeprecatedSince20
________________ test_is_url_false[https://example.com-dirty1] _________________

other = 'https://example.com'
dirty = IsUrl(<class 'pydantic_core._pydantic_core.Url'>)

    @pytest.mark.parametrize(
        'other,dirty',
        [
            ('https://example.com', IsUrl(postgres_dsn=True)),
            ('https://example.com', IsUrl(scheme='http')),
            ('definitely not a url', IsUrl),
            (42, IsUrl),
            ('https://anotherexample.com', IsUrl(postgres_dsn=True)),
        ],
    )
    def test_is_url_false(other, dirty):
>       assert other != dirty

tests/test_other.py:297:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
dirty_equals/_base.py:114: in __ne__
    return not self.equals(other)
dirty_equals/_other.py:264: in equals
    parsed = self.parse_obj_as(self.url_type, other)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

args = (<class 'pydantic_core._pydantic_core.Url'>, 'https://example.com')
kwargs = {}

    @functools.wraps(arg)
    def wrapper(*args, **kwargs):
>       warnings.warn(msg, category=category, stacklevel=stacklevel + 1)
E       pydantic.warnings.PydanticDeprecatedSince20: parse_obj_as is deprecated. Use pydantic.TypeAdapter.validate_python instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.4/migration/

/usr/lib/python3.8/site-packages/typing_extensions.py:2359: PydanticDeprecatedSince20
________________ test_is_url_false[definitely not a url-IsUrl] _________________

other = 'definitely not a url', dirty = IsUrl

    @pytest.mark.parametrize(
        'other,dirty',
        [
            ('https://example.com', IsUrl(postgres_dsn=True)),
            ('https://example.com', IsUrl(scheme='http')),
            ('definitely not a url', IsUrl),
            (42, IsUrl),
            ('https://anotherexample.com', IsUrl(postgres_dsn=True)),
        ],
    )
    def test_is_url_false(other, dirty):
>       assert other != dirty

tests/test_other.py:297:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
dirty_equals/_base.py:26: in __eq__
    return self() == other
dirty_equals/_base.py:104: in __eq__
    self._was_equal = self.equals(other)
dirty_equals/_other.py:264: in equals
    parsed = self.parse_obj_as(self.url_type, other)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

args = (<class 'pydantic_core._pydantic_core.Url'>, 'definitely not a url')
kwargs = {}

    @functools.wraps(arg)
    def wrapper(*args, **kwargs):
>       warnings.warn(msg, category=category, stacklevel=stacklevel + 1)
E       pydantic.warnings.PydanticDeprecatedSince20: parse_obj_as is deprecated. Use pydantic.TypeAdapter.validate_python instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.4/migration/

/usr/lib/python3.8/site-packages/typing_extensions.py:2359: PydanticDeprecatedSince20
_________________________ test_is_url_false[42-IsUrl] __________________________

other = 42, dirty = IsUrl

    @pytest.mark.parametrize(
        'other,dirty',
        [
            ('https://example.com', IsUrl(postgres_dsn=True)),
            ('https://example.com', IsUrl(scheme='http')),
            ('definitely not a url', IsUrl),
            (42, IsUrl),
            ('https://anotherexample.com', IsUrl(postgres_dsn=True)),
        ],
    )
    def test_is_url_false(other, dirty):
>       assert other != dirty

tests/test_other.py:297:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
dirty_equals/_base.py:26: in __eq__
    return self() == other
dirty_equals/_base.py:104: in __eq__
    self._was_equal = self.equals(other)
dirty_equals/_other.py:264: in equals
    parsed = self.parse_obj_as(self.url_type, other)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

args = (<class 'pydantic_core._pydantic_core.Url'>, 42), kwargs = {}

    @functools.wraps(arg)
    def wrapper(*args, **kwargs):
>       warnings.warn(msg, category=category, stacklevel=stacklevel + 1)
E       pydantic.warnings.PydanticDeprecatedSince20: parse_obj_as is deprecated. Use pydantic.TypeAdapter.validate_python instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.4/migration/

/usr/lib/python3.8/site-packages/typing_extensions.py:2359: PydanticDeprecatedSince20
_____________ test_is_url_false[https://anotherexample.com-dirty4] _____________

other = 'https://anotherexample.com'
dirty = IsUrl(typing_extensions.Annotated[pydantic_core._pydantic_core.MultiHostUrl, UrlConstraints(max_length=None, allowed_s...+py-postgresql', 'postgresql+pygresql'], host_required=True, default_host=None, default_port=None, default_path=None)])

    @pytest.mark.parametrize(
        'other,dirty',
        [
            ('https://example.com', IsUrl(postgres_dsn=True)),
            ('https://example.com', IsUrl(scheme='http')),
            ('definitely not a url', IsUrl),
            (42, IsUrl),
            ('https://anotherexample.com', IsUrl(postgres_dsn=True)),
        ],
    )
    def test_is_url_false(other, dirty):
>       assert other != dirty

tests/test_other.py:297:
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
dirty_equals/_base.py:114: in __ne__
    return not self.equals(other)
dirty_equals/_other.py:264: in equals
    parsed = self.parse_obj_as(self.url_type, other)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

args = (typing_extensions.Annotated[pydantic_core._pydantic_core.MultiHostUrl, UrlConstraints(max_length=None, allowed_scheme...ygresql'], host_required=True, default_host=None, default_port=None, default_path=None)], 'https://anotherexample.com')
kwargs = {}

    @functools.wraps(arg)
    def wrapper(*args, **kwargs):
>       warnings.warn(msg, category=category, stacklevel=stacklevel + 1)
E       pydantic.warnings.PydanticDeprecatedSince20: parse_obj_as is deprecated. Use pydantic.TypeAdapter.validate_python instead. Deprecated in Pydantic V2.0 to be removed in V3.0. See Pydantic V2 Migration Guide at https://errors.pydantic.dev/2.4/migration/

/usr/lib/python3.8/site-packages/typing_extensions.py:2359: PydanticDeprecatedSince20
=========================== short test summary info ============================
FAILED tests/test_other.py::test_is_url_true[https://example.com-IsUrl] - pyd...
FAILED tests/test_other.py::test_is_url_true[https://example.com-dirty1] - py...
FAILED tests/test_other.py::test_is_url_true[postgres://user:pass@localhost:5432/app-dirty2]
FAILED tests/test_other.py::test_is_url_false[https://example.com-dirty0] - p...
FAILED tests/test_other.py::test_is_url_false[https://example.com-dirty1] - p...
FAILED tests/test_other.py::test_is_url_false[definitely not a url-IsUrl] - p...
FAILED tests/test_other.py::test_is_url_false[42-IsUrl] - pydantic.warnings.P...
FAILED tests/test_other.py::test_is_url_false[https://anotherexample.com-dirty4]
======================== 8 failed, 539 passed in 1.32s =========================
```
</details>

**Comment by gotmax23** [comment] 2023-11-10 18:26
Dupe of https://github.com/samuelcolvin/dirty-equals/issues/72

**Closed** 2023-11-14 09:34 UTC
